### ISSUE TITLE
YAML files use old API version

### ISSUE THREAD

**Issue by ToddKopriva** [GoogleCloudPlatform/gke-deployment-testing-strategies#1]
In /canary/deployment-old.yaml and similar files, the v1beta version of the API throws an error (no matches for kind "Deployment").

The YAML files need to be updated to v1 (apiVersion: apps/v1beta1 -> apiVersion: apps/v1), and they need a selector tag with that update.

**Comment by mail2shobz** [comment]
in bluegreen  yaml also same issue is there

**Comment by prakhag2** [comment]
Merged a PR to resolve the issue.
